modLoader="javafml" #mandatory
loaderVersion="[4,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="MIT"

[[mods]] #mandatory

modId="vanillafix" #mandatory

version="${version}" #mandatory
authors = "repletsin5"
displayName="Vanilla Icecream Fix" #mandatory
logoFile="icon.png" #optional
issueTrackerURL = "https://github.com/repletsin5/VanillaIcecreamFix/issues"
description='''

'''
[[dependencies.vanillafix]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.vanillafix]]
mandatory=true #mandatory
modId = "neoforge"
type = "required"
versionRange = "[21.0.0-beta,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.vanillafix]]
mandatory=true #mandatory
modId = "cloth_config"
type = "required"
versionRange = "[15.0.0,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "vanillafix.bugs.mixins.json"
[[mixins]]
config = "vanillafix.crashui.mixins.json"
[[mixins]]
config = "vanillafix.textures.mixins.json"
[[mixins]]
config = "vanillafix.other.mixins.json"